language: php
dist: trusty
sudo: required

services:
  - docker

env:
 - PECL_HTTP_VERSION=3.1.1RC1

php:
  - 7.2
  - 7.1
  - 7.0

before_install:
  - docker build -t datawraith/p7zip test/integration
  - composer install --dev
  - sudo apt-get install unzip libgnutls-dev
  - pecl channel-update pecl.php.net
  - printf "\n\n\n" | pecl install pecl_http-$PECL_HTTP_VERSION

script:
 - vendor/bin/phpunit --configuration test/phpunit.xml

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: PECL_HTTP_VERSION=2.6.0

